apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstarp-crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kanzifucius/argocd-k8-platfrom-bootstrap.git'
    path: argo-bootstrap/crossplane
    targetRevision: master
    directory:
      recurse: true
      jsonnet: { }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstarp-platfrom
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: crossplane
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-bootstrap/bootstraps
    repoURL: 'https://github.com/kanzifucius/argocd-k8-platfrom-bootstrap.git'
    targetRevision: master
  project: default
  directory:
    recurse: true
    jsonnet: { }
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
